// <auto-generated />
namespace Backend.Migrations.SeedData
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Update_User : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Update_User));
        
        string IMigrationMetadata.Id
        {
            get { return "201709210203343_Update_User"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
